class Genres:
    """
    Source: http://everynoise.com/everynoise1d.cgi?scope=all
    """

    IDS = [
        'focus', 
        'classic soul', 
        'classical', 
        'compositional ambient', 
        'lo-fi beats', 
        'sleep', 
        'soundtrack', 
        'scorecore', 
        'neo-classical', 
        'cool jazz', 
        'jazz', 
        'classify', 
        'new age', 
        'german soundtrack', 
        'ambient', 
        'early romantic era', 
        'classical era', 
        'piano cover', 
        'atmosphere', 
        'chill guitar', 
        'new age piano', 
        'drone', 
        'relaxative', 
        'chill beats', 
        'polish classical', 
        'minimal', 
        'pianissimo', 
        'drift', 
        'canadian soundtrack', 
        'russian romanticism', 
        'japanese classical', 
        'pet calming', 
        'icelandic classical', 
        'brain waves', 
        'contemporary classical', 
        'theme', 
        'american contemporary classical', 
        'italian soundtrack', 
        'ballet class', 
        'canadian classical',
    ]